version: '2'

services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/myapp/vendor/bundle
      - bundle:/myapp/.bundle
      - bundle_cache:/usr/local/bundle
  web:
    depends_on:
      - db
    volumes:
      - .:/myapp
    volumes_from:
      - datastore
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-rails.dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes_from:
      - datastore
    volumes:
      - ./db/mysql_data:/var/lib/mysql

volumes:
  bundle_install:
    driver: local
  bundle:
    driver: local
  bundle_cache:
    driver: local
