version: '2'

services:
  web:
    depends_on:
      - db
    volumes:
      - .:/myapp
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-rails.dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
